language: php

dist: xenial

notifications:
  email:
    on_success: never

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

cache:
  directories:
    - $HOME/.composer/cache

env:
  matrix:
    - PREFER_LOWEST="--prefer-lowest" INSTALL_BINARY="sudo apt-get install -y brotli"
    - PREFER_LOWEST="" INSTALL_BINARY="sudo apt-get install -y brotli"

before_script:
  - $INSTALL_BINARY
  - composer update --no-interaction $PREFER_LOWEST

script:
  - vendor/bin/phpunit
